authing/urls.py
from django.urls import path

from . import views

app_name = 'authing'
urlpatterns = [
    path('', views.login_user, name='login_user'),
    path('', views.logout_user, name='logout_user'),
]

sms_app/urls.py
from django.urls import path

from . import views

app_name = 'sms_app'
urlpatterns = [
    path('', views.index, name='index'),
    path('sms_form/', views.sms_form, name='sms_form'),
]

sms_project/urls.py
from django.contrib import admin
from django.contrib.auth import views as auth_views, urls
from django.contrib.auth.decorators import login_required
from django.urls import include, path

urlpatterns = [
    path('', include('authing.urls')),
    path('admin/', admin.site.urls),
    path('sms_app/', include('sms_app.urls')),
]

authing/models.py
from django.db import models

# Create your models here.

sms_app/models.py
from datetime import timedelta
from django.db import models
from django.utils import timezone
from phonenumber_field.modelfields import PhoneNumberField

class Message(models.Model):
    sms_id = models.CharField(max_length=50, null=False, blank=False, primary_key=True)
    number = PhoneNumberField(null=False, blank=False)
    message = models.CharField(max_length=200)
    status = models.CharField(max_length=20)
    date = models.DateTimeField('date sent')
    
    def __str__(self):
        return f"{self.number} | {self.message} | {self.status} | {self.date}"

    def was_sent_recently(self):
        return self.date >= timezone.now() - timedelta(days=1)

authing/views.py
from django.http import HttpResponseRedirect
from django.shortcuts import render
from django.contrib.auth import views
from django.contrib.auth import authenticate, login, logout
from django.urls import reverse


def login_user(request):
    if request.method == "POST":
        username = request.POST['username']
        password = request.POST['password']

        user = authenticate(request, username=username, password=password)
        if user is not None and user.is_authenticated:
            login(request, user)
            return HttpResponseRedirect(reverse('sms_app:index'))
        else:
            context = {
                "error": "There Was An Error Logging In, Try Again...",
                "html": views.LoginView.form_class(),
            }
            return render(request, 'login.html', context)

    else:
        logout_user(request)
        context = {
                "html": views.LoginView.form_class(),
            }
        return render(request, 'login.html', context)

def logout_user(request):
    logout(request)
    return HttpResponseRedirect(reverse('authing:login_user'))

sms_app/views.py
from datetime import datetime
from psycopg2 import OperationalError
from requests import RequestException

from django.contrib.auth import views
from django.contrib.auth.decorators import login_required
from django.urls import reverse
from django.http import HttpResponseRedirect
from django.shortcuts import redirect, render

from twilio.base.exceptions import TwilioRestException
from twilio.rest import Client

from .models import Message

import phonenumbers
import os


env_twilio_sid = os.environ.get('TA_SID')
env_twilio_token = os.environ.get('TA_TOKEN')
client = Client(env_twilio_sid, env_twilio_token) 

def authenticate(request):
    print("AUTH:",request.user,request.user.is_authenticated, request.user.is_anonymous)
    print(request.__str__())
    if not request.user.is_authenticated or request.user.is_anonymous:
        print( "USER:", request.user )
        context = {
                "error": "There Was An Error Logging In, Try Again...",
                "html": views.LoginView.form_class(),
            }
        return redirect('/')
        #return HttpResponseRedirect(reverse('login_user', args=[1945]))

@login_required
def index(request):
    reload_status()
    print(request)

    try:
        sms_list = Message.objects.order_by('date')[::-1]
    except OperationalError:
        context = {
            'db_error': "Unable to connect to database",
            }
        return render(request, 'index.html', context)
    else:
        context = {
            'sms_list': sms_list[:8],
            }
        return render(request, 'index.html', context)
    

def reload_status():
    queued = Message.objects.filter( status="queued" )
    queued_sids = [ msg.sms_id for msg in queued ]

    for sid in queued_sids:
        try:            
            message_status = client.messages.get(sid).fetch().status
            message = Message.objects.filter( sms_id = sid )
            for msg in message:
                msg.status = message_status
                msg.save()

        except TwilioRestException:
            print( f"Message with sid {sid} failed to obtain status" )

        except RequestException:
            print( f"Network request failure" )

@login_required
def sms_form(request):
    if request.method == "POST":
        return send_sms(request)

    return render(request, 'sms_form.html', {})

def number_message_check(number, message):
    parsed_phone_number = phonenumbers.parse( number )
    if not message or not number:
        raise ValueError("Please enter a message or a number.")
    elif len( message ) > 160:
        raise ValueError("Message to long, keep it under 160 characters.")
    elif not phonenumbers.is_valid_number_for_region(parsed_phone_number, "ZA"):
        raise phonenumbers.NumberParseException

    return parsed_phone_number

@login_required
def send_sms(request):
    print("req", request)
    sms = {
        "message": request.POST['message'], 
        "number": request.POST['number'],
        }
    try:
        parsed_phone_number = number_message_check( sms["number"], sms["message"] )

    except ValueError as e:
        print("############################################################")
        return render(request, 'sms_form.html', {
            'message_error': e,
        })

    except phonenumbers.NumberParseException:
        print("############################################################")
        return render(request, 'sms_form.html', {
            'number_error': "Number not valid",
        })

    else:
        sms["parsed_phone_number"] = parsed_phone_number

    try:
        print("Sending SMS...")
        message = client.messages.create(
                    body=sms["message"],
                    from_='+15076291974',
                    to=sms["number"], 
                    provide_feedback=True,
                )

    except RequestException as e:
        return render(request, 'sms_form.html', {
            'network_error': "Network Error Request Failed.",
        })
    except TwilioRestException as e:
        print(e)
        return render(request, 'sms_form.html', {
            'number_error': "Number is unverified.",
        })
    else:
        print("SMS Sent")
        sms_sql = Message( sms_id = message.sid, number = sms["parsed_phone_number"], 
                message = sms["message"], status=message.status, date=datetime.now() )
        sms_sql.save()
        # Always return an HttpResponseRedirect after successfully dealing with POST data.
        # This prevents data from being posted twice if a user hits the Back button.
        return HttpResponseRedirect(reverse('sms_app:index'))

authing/templates/login.html
<form action="{% url 'authing:login_user' %}" method="post"> {% csrf_token %}
    {% if error %}
        <p style="color:red">
            {{ error }}
        </p>
    {% endif %}
    <fieldset>
        <legend><h1>Login</h1></legend>
        {% if html %}
            {{ html }}
        {% endif %}
    </fieldset>
    <input type="submit" value="Send">
</form>

sms_app/templates/index.html
<div>
    <span style="float:right">
        <a href="{% url 'authing:logout_user' %}"><h4>Logout</h4> </a>
    </span>
    <span>
        <h2>Form to send a message to a number</h2> <a href="{% url 'sms_app:sms_form' %}">Send a SMS</a>
    </span>
</div>

{% if db_error %}
<h1>{{ db_error }}</h1>
{% endif %}

{% if sms_list %}
<div>
    <h1>List of messages</h1> <a href="{% url 'sms_app:index' %}">Reload SMS Status</a>
</div>
    <div style="display: grid; grid-template-columns: 33% 33% 33%; float:left">
    {% for sms in sms_list %}
        <div style="background-color: #ddd; border-radius: 25px; margin: 5px; padding: 5px;">
            <p>To: <b>{{ sms.number }}</b></p>
            <p>Message: <b>{{ sms.message }}</b></p>
            <p>Status: <b>{{ sms.status }}</b></p>
            <p>Date: <b>{{ sms.date }}</b></p>
        </div>
    {% endfor %}
    </div>
{% else %}
    <h1>No messages are available.</h1>
{% endif %}

sms_app/templates/sms_form.html
<form action="{% url 'sms_app:sms_form' %}" method="post">
    {% if network_error %}
        <p style="color:red">
            {{ network_error }}
        </p>
        {% endif %}
    {% csrf_token %}
    <fieldset>
        <legend><h1>Compose message</h1></legend>
        {% if number_error %}
        <p style="color:red">
            {{ number_error }}
        </p>
        {% endif %}
        <label>Phone Number</label>
        <input type="text" name="number" id="number" value="">
        <br><br>
        {% if message_error %}
        <p style="color:red">
            {{ message_error }}
        </p>
        {% endif %}
        <label>Message</label>
        <input type="text" name="message" id="message" value="">
        <br>
    </fieldset>
    <input type="submit" value="Send">
</form>
    <a href="{% url 'sms_app:index' %}">Go Back</a>
</div>